repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.4.0
   hooks:
     - id: check-merge-conflict
     - id: check-yaml
     - id: end-of-file-fixer
     - id: requirements-txt-fixer
     - id: trailing-whitespace
- repo: https://github.com/PyCQA/autoflake
  rev: v2.1.1
  hooks:
    - id: autoflake
      args: [--in-place, --remove-all-unused-imports]
      exclude: "conftest.py"
- repo: https://github.com/PyCQA/isort
  rev: 5.11.5
  hooks:
    - id: isort
      args: ["--profile", "black"]
      exclude: "conftest.py"
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
    - id: black
      exclude: "conftest.py"
